# Router firewall: the default `inet tui` nftables table.
#
# This replaces the server profile's install/server/firewall-server.sh (ufw).
# A router's job is to forward and NAT, which ufw's host-oriented model does
# not express cleanly, and the tui-firewall tool -- the one this profile hands
# the operator through the `tui-tools` addon -- manages a native nftables table
# named `inet tui`. So the profile writes exactly that table as the default,
# and the tool and the seed agree on one manager of one subsystem.
#
# The default policy (router-1.0):
#   input    drop, except: established/related, loopback, ICMP, everything from
#            the LAN, and from the WAN only 22/tcp and the WireGuard UDP port.
#   forward  drop, except: established/related and LAN -> WAN. WAN -> LAN is
#            return traffic only, which conntrack already accepts.
#   nat      masquerade out of the WAN. This is the NAT default.
#
# Exposed to the WAN, and nothing else: 22/tcp (ssh) and the WireGuard UDP port
# (/etc/omarchy/router/wireguard.env, default 51820). No web port. No
# management daemon. The tui-tools are terminal UIs the operator runs at the
# console or over ssh; none of them listens.
#
# "Previewed, not hidden": the ruleset is this plain file at /etc/nftables.conf,
# which nftables.service loads at boot -- so the machine is never open while it
# waits for an operator -- and `omarchy-router-firewall` prints it and re-applies
# it on confirm, the same command-preview-then-confirm contract the tui-tools
# follow. This script only writes the file and enables the loader; it never runs
# `nft` against the live ruleset (it runs inside the ISO's install chroot, where
# there is no router to apply it to).

install -d -m 0755 /etc/omarchy/router

# The WireGuard port the WAN rule opens. A file so a deployment can move it
# without editing the ruleset, and so omarchy-router-firewall reads the same
# value when it regenerates the table.
wg_env=/etc/omarchy/router/wireguard.env
if [[ ! -f $wg_env ]]; then
  cat >"$wg_env" <<'EOF'
# Omarchy Router: the WireGuard listen port opened on the WAN. Change it here
# and run `omarchy-router-firewall` to regenerate /etc/nftables.conf.
WG_PORT=51820
EOF
  chmod 0644 "$wg_env"
fi
wg_port=51820
# shellcheck disable=SC1090
[[ -r $wg_env ]] && source "$wg_env"
[[ ${WG_PORT:-} =~ ^[0-9]+$ ]] && wg_port="$WG_PORT"

# The ruleset. Generated here at install and regenerated by
# omarchy-router-firewall; both write the identical table so an operator can
# diff what is on disk against what the tool would produce.
cat >/etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# Omarchy Router default firewall. Written by
# install/router/firewall-router.sh and regenerated by
# \`omarchy-router-firewall\`. Managed live by tui-firewall (the \`tui-tools\`
# addon), whose native table this is.
#
# Roles are the stable link names wan0 (uplink) and lan0 (internal); see
# install/router/network-router.sh. Exposed to the WAN: 22/tcp and udp/$wg_port
# (WireGuard) only.
flush ruleset

table inet tui {
  chain input {
    type filter hook input priority filter; policy drop;

    ct state established,related accept
    ct state invalid drop
    iif "lo" accept

    # Diagnostics and path-MTU discovery.
    meta l4proto icmp accept
    meta l4proto ipv6-icmp accept

    # The LAN is trusted for host services: ssh, the DHCP server on lan0
    # (udp/67) and this router as the LAN's resolver (udp/53, tcp/53).
    iifname "lan0" accept

    # The WAN answers on exactly two ports.
    iifname "wan0" tcp dport 22 accept
    iifname "wan0" udp dport $wg_port accept
  }

  chain forward {
    type filter hook forward priority filter; policy drop;

    ct state established,related accept
    ct state invalid drop

    # LAN clients reach the internet. WAN -> LAN is return traffic only, which
    # the conntrack rule above already accepts; there is no other WAN -> LAN
    # rule on purpose.
    iifname "lan0" oifname "wan0" accept

    # A WireGuard peer that should reach the LAN gets its rule when the tunnel
    # is configured (tui-vpn, when released, or by hand):
    #   iifname "wg0" oifname "lan0" accept
    #   iifname "lan0" oifname "wg0" accept
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;

    # Source-NAT LAN traffic behind the WAN address. This is the NAT default.
    oifname "wan0" masquerade
  }
}
EOF
chmod 0755 /etc/nftables.conf

# nftables.service loads /etc/nftables.conf at boot. This is what makes the
# default safe from the first second, before any operator logs in.
systemctl enable nftables.service

# The router has no ufw. If a dependency ever dragged it in, a masked unit
# cannot start and cannot be pulled in by another unit's Wants=.
systemctl mask ufw.service 2>/dev/null || true
